apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: custfe-cluster-ip-service
                port:
                  number: 80
          - path: /docs/(.*)
            pathType: Prefix
            backend:
              service:
                name: custapi-cluster-ip-service
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: custapi-cluster-ip-service
                port:
                  number: 80
