apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress
  namespace: parivattam
#   annotations:
#     konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: custfe-cluster-ip-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /monitoring
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /monitoring/ui
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /monitoring/stats
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80
      - path: /monitoring/metrics
        pathType: Prefix
        backend:
          service:
            name: custapi-cluster-ip-service
            port:
              number: 80

