---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azfs-data
  namespace: monitoring
  labels:
    type: azurefs
    app: prometheus-deployment
spec:
  storageClassName: azure-file-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: prometheus
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl