---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azfs-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: azure-file-prometheus-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
