---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azfs-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: azure-file-sc
  accessModes:
    - ReadWriteMany
  # volumeName: pv-azfs-prometheus
  resources:
    requests:
      storage: 1Gi
