apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azfs-grafana
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: azure-file-grafana-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: grafana
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl