apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azfs-storage
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: azure-file-grafana-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
