apiVersion: apps/v1
kind: Deployment
metadata:
  name: custfe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custfe
  template:
    metadata:
      labels:
        component: custfe
    spec:
      containers:
        - name: teakadaicustomerfe
          image:  teakadaiacr.azurecr.io/customer-portal-fe
          ports:
            - containerPort: 80
      imagePullSecrets:
            - name: tekadai-acr-secret
