apiVersion: apps/v1
kind: Deployment
metadata:
  name: teakadai-api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/monitoring/metrics'
    prometheus.io/port: '80'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teakadai-api
  template:
    metadata:
      labels:
        app: teakadai-api
    spec:
      containers:
        - name: teakadai-api
          image:  teakadaiacr.azurecr.io/customer-api
          ports:
          - name: web
            containerPort: 80
      imagePullSecrets:
        - name: tekadai-acr-secret
