apiVersion: v1
kind: Service
metadata:
  name: teakadai-api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/monitoring/metrics'
    prometheus.io/port: '80'
  labels:
    app: teakadai-api
spec:
  type: ClusterIP
  selector:
    app: teakadai-api
  ports:
  - name: web
    port: 80
