apiVersion: v1
kind: Service
metadata:
  name: custapi-cluster-ip-service
  labels:
    app: custapi-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: custapi
  ports:
    - port: 80
      targetPort: 80
