apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: teakadai-api-pod-mon
  labels:
    team: restapi
spec:
  selector:
    matchLabels:
      app: teakadai-api
  podMetricsEndpoints:
  - port: web
    path: /monitoring/metrics
    interval: 5s
  namespaceSelector:
    matchNames:
      - parivattam
