apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: teakadai-api
  labels:
    team: restapi
spec:
  selector:
    matchLabels:
      app: teakadai-api
  endpoints:
  - port: web
    path: /monitoring/metrics
